# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jackydjl/project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jackydjl/project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jackydjl/project2/CMakeFiles /home/jackydjl/project2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jackydjl/project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calculator

# Build rule for target.
calculator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculator
.PHONY : calculator

# fast build rule for target.
calculator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/build
.PHONY : calculator/fast

Add.o: Add.cpp.o
.PHONY : Add.o

# target to build an object file
Add.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Add.cpp.o
.PHONY : Add.cpp.o

Add.i: Add.cpp.i
.PHONY : Add.i

# target to preprocess a source file
Add.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Add.cpp.i
.PHONY : Add.cpp.i

Add.s: Add.cpp.s
.PHONY : Add.s

# target to generate assembly for a file
Add.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Add.cpp.s
.PHONY : Add.cpp.s

DeleteKuohao.o: DeleteKuohao.cpp.o
.PHONY : DeleteKuohao.o

# target to build an object file
DeleteKuohao.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/DeleteKuohao.cpp.o
.PHONY : DeleteKuohao.cpp.o

DeleteKuohao.i: DeleteKuohao.cpp.i
.PHONY : DeleteKuohao.i

# target to preprocess a source file
DeleteKuohao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/DeleteKuohao.cpp.i
.PHONY : DeleteKuohao.cpp.i

DeleteKuohao.s: DeleteKuohao.cpp.s
.PHONY : DeleteKuohao.s

# target to generate assembly for a file
DeleteKuohao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/DeleteKuohao.cpp.s
.PHONY : DeleteKuohao.cpp.s

Divide.o: Divide.cpp.o
.PHONY : Divide.o

# target to build an object file
Divide.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Divide.cpp.o
.PHONY : Divide.cpp.o

Divide.i: Divide.cpp.i
.PHONY : Divide.i

# target to preprocess a source file
Divide.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Divide.cpp.i
.PHONY : Divide.cpp.i

Divide.s: Divide.cpp.s
.PHONY : Divide.s

# target to generate assembly for a file
Divide.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Divide.cpp.s
.PHONY : Divide.cpp.s

Minus.o: Minus.cpp.o
.PHONY : Minus.o

# target to build an object file
Minus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Minus.cpp.o
.PHONY : Minus.cpp.o

Minus.i: Minus.cpp.i
.PHONY : Minus.i

# target to preprocess a source file
Minus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Minus.cpp.i
.PHONY : Minus.cpp.i

Minus.s: Minus.cpp.s
.PHONY : Minus.s

# target to generate assembly for a file
Minus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Minus.cpp.s
.PHONY : Minus.cpp.s

Multiply.o: Multiply.cpp.o
.PHONY : Multiply.o

# target to build an object file
Multiply.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Multiply.cpp.o
.PHONY : Multiply.cpp.o

Multiply.i: Multiply.cpp.i
.PHONY : Multiply.i

# target to preprocess a source file
Multiply.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Multiply.cpp.i
.PHONY : Multiply.cpp.i

Multiply.s: Multiply.cpp.s
.PHONY : Multiply.s

# target to generate assembly for a file
Multiply.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/Multiply.cpp.s
.PHONY : Multiply.cpp.s

calculator.o: calculator.cpp.o
.PHONY : calculator.o

# target to build an object file
calculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calculator.cpp.o
.PHONY : calculator.cpp.o

calculator.i: calculator.cpp.i
.PHONY : calculator.i

# target to preprocess a source file
calculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calculator.cpp.i
.PHONY : calculator.cpp.i

calculator.s: calculator.cpp.s
.PHONY : calculator.s

# target to generate assembly for a file
calculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/calculator.cpp.s
.PHONY : calculator.cpp.s

judgeIllegalInput.o: judgeIllegalInput.cpp.o
.PHONY : judgeIllegalInput.o

# target to build an object file
judgeIllegalInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/judgeIllegalInput.cpp.o
.PHONY : judgeIllegalInput.cpp.o

judgeIllegalInput.i: judgeIllegalInput.cpp.i
.PHONY : judgeIllegalInput.i

# target to preprocess a source file
judgeIllegalInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/judgeIllegalInput.cpp.i
.PHONY : judgeIllegalInput.cpp.i

judgeIllegalInput.s: judgeIllegalInput.cpp.s
.PHONY : judgeIllegalInput.s

# target to generate assembly for a file
judgeIllegalInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator.dir/build.make CMakeFiles/calculator.dir/judgeIllegalInput.cpp.s
.PHONY : judgeIllegalInput.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... calculator"
	@echo "... Add.o"
	@echo "... Add.i"
	@echo "... Add.s"
	@echo "... DeleteKuohao.o"
	@echo "... DeleteKuohao.i"
	@echo "... DeleteKuohao.s"
	@echo "... Divide.o"
	@echo "... Divide.i"
	@echo "... Divide.s"
	@echo "... Minus.o"
	@echo "... Minus.i"
	@echo "... Minus.s"
	@echo "... Multiply.o"
	@echo "... Multiply.i"
	@echo "... Multiply.s"
	@echo "... calculator.o"
	@echo "... calculator.i"
	@echo "... calculator.s"
	@echo "... judgeIllegalInput.o"
	@echo "... judgeIllegalInput.i"
	@echo "... judgeIllegalInput.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

